const life = gi('life'),
    startButton = gi('start'),
    bestScore = gi('bestScore'),
    lastScore = gi('lastScore'),
    startScreen = gi('startScreen')
    seeTheStory = gi('seeTheStory'),
    startCounter = gi('startCounter'),
    nextSongButton = gi('nextSongButton');
let canvas = qs('canvas');
let storyContainer = qs('.container p');